# Generated by Django 4.0.4 on 2022-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.CharField(max_length=100, verbose_name='From')),
                ('to_field', models.CharField(max_length=100, verbose_name='To')),
                ('type_of_trip', models.CharField(choices=[('Round Trip', 'Round Trip'), ('One Way', 'One Way')], default='One Way', max_length=100, verbose_name='Trip Type')),
                ('passengers', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Passengers')),
                ('shop_with_roytec', models.BooleanField(verbose_name='Shop with Roytec')),
                ('refundable', models.BooleanField(verbose_name='Refundable Fares')),
                ('date_flex', models.BooleanField(verbose_name='My Dates are Flexible')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(default='', max_length=254, verbose_name='*Email Address')),
                ('first_name', models.CharField(max_length=150, verbose_name='*First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='*Last Name')),
                ('country', models.CharField(max_length=200, verbose_name='*Country')),
            ],
        ),
    ]
